// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsTxALxIwDBHHBCtYPWwkUYGj1hNO93g',
    appId: '1:910778107409:web:c50d636919055f4d8e13b0',
    messagingSenderId: '910778107409',
    projectId: 'chat-app-c40d9',
    authDomain: 'chat-app-c40d9.firebaseapp.com',
    storageBucket: 'chat-app-c40d9.appspot.com',
    measurementId: 'G-Y7KZ953EP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-i7K6LWQ1yK2kD6N7dHJ244Gu7Xp50E',
    appId: '1:910778107409:android:56063822f2d87b2c8e13b0',
    messagingSenderId: '910778107409',
    projectId: 'chat-app-c40d9',
    storageBucket: 'chat-app-c40d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1X9qRpVwwZ0OUggb2S1w0j9sCYVOVG0s',
    appId: '1:910778107409:ios:4a3cc34995bbe36b8e13b0',
    messagingSenderId: '910778107409',
    projectId: 'chat-app-c40d9',
    storageBucket: 'chat-app-c40d9.appspot.com',
    iosClientId: '910778107409-mi0h46guv83c34p975f76utq4612ll8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1X9qRpVwwZ0OUggb2S1w0j9sCYVOVG0s',
    appId: '1:910778107409:ios:4a3cc34995bbe36b8e13b0',
    messagingSenderId: '910778107409',
    projectId: 'chat-app-c40d9',
    storageBucket: 'chat-app-c40d9.appspot.com',
    iosClientId: '910778107409-mi0h46guv83c34p975f76utq4612ll8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
